name: "tvm-python x86_64 Linux"

on: [push,workflow_dispatch,workflow_call]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        python: [39, 310, 311]
    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      env:
        USER: runner

    - uses: cachix/cachix-action@v12
      with:
        name: disintar
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      env:
        USER: runner

    - name: Compile
      run: nix build .?submodules=1#packages.x86_64-linux.ton-python-${{ matrix.python }}
           --print-build-logs --system x86_64-linux -o result-x86_64

    - name: Copy binaries
      run: |
        ls -lart 
        mkdir artifacts
        cp $PWD/result-x86_64/lib/* artifacts/

    - name: Simple binaries test
      run: nix develop .#packages.x86_64-linux.ton-python-${{ matrix.python }}
           -c bash -c "cd artifacts; python3 -c 'import python_ton'"

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-x86_64-linux-python-${{ matrix.python }}
        path: artifacts