name: "tvm-python master"

on:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master ]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        os: [macos-12]
        python: [39, 310, 311]
        exclude:
          - # covered by ton-x86_64-linux-python.yml
            os: ubuntu-22.04
            arch: x86_64
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install QEMU
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-22.04" ]; then
          sudo apt update
          sudo apt install -y apt-utils
          sudo apt install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
        elif [ "${{ matrix.os }}" = "macos-12" ]; then
          brew install qemu
        fi

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          
    - run: |
        echo "SYSTEM=$(nix eval --raw 'nixpkgs#system')" >> $GITHUB_ENV
        echo "ARCH=$(nix eval --raw 'nixpkgs#hostPlatform.parsed.cpu.name')" >> $GITHUB_ENV

    - name: Compile
      run: nix build .?submodules=1#packages."$SYSTEM".ton-python-${{ matrix.python }}
           --print-build-logs --system "$SYSTEM" -o result-"$ARCH"

    - name: Copy binaries
      run: |
        ls -lart 
        mkdir artifacts
        cp $PWD/result-"$ARCH"/lib/* artifacts/

    - name: Simple binaries test
      run: nix develop .#packages."$SYSTEM".ton-python-${{ matrix.python }}
           -c bash -c "cd artifacts; python3 -c 'import python_ton'"

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-${{ env.SYSTEM }}-python-${{ matrix.python }}
        path: artifacts
