name: "tvm-python master"

on:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master ]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        os: [macos-12]
        python: [39, 310, 311]
        include:
          - os: ubuntu-22.04
            arch: aarch64
    runs-on: ubuntu-22.04

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Compile
      run: nix build .?submodules=1#packages.${{ matrix.arch }}-${{ matrix.os }}.ton-python-${{ matrix.python }}
           --print-build-logs --system ${{ matrix.arch }}-${{ matrix.os }} -o result-${{ matrix.arch }}

    - name: Copy binaries
      run: |
        ls -lart 
        mkdir artifacts
        cp $PWD/result-${{ matrix.arch }}/lib/* artifacts/

    - name: Simple binaries test
      run: nix develop .#packages.${{ matrix.arch }}-${{ matrix.os }}.ton-python-${{ matrix.python }}
           -c bash -c "cd artifacts; python3 -c 'import python_ton'"

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-${{ matrix.arch }}-${{ matrix.os }}-python-${{ matrix.python }}
        path: artifacts